//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_hunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Foods = new HashSet<Food>();
        }
    
        public int id { get; set; }
        public string status { get; set; }
        public System.DateTime order_time { get; set; }
        public System.DateTime expire_time { get; set; }
        public int total_quantity { get; set; }
        public int restaurant_id { get; set; }
        public int employee_id { get; set; }
        public int admin_id { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Foods { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
